"""Learning-material page renderer (user feedback round 3).

One pre-styled, self-contained HTML template; generated materials (explainers,
images, video embeds, self-checks) are slotted into it so every artifact the
harness produces shares a clean, consistent look. No external requests.

Usage (from skills or the agent):
    from harness.material_page import build_material_page
    build_material_page(root, title="...", kc="concurrency",
                        body_html="<p>...</p>", image="diagram.png",
                        video="clip.mp4", questions=["...?"])
Writes learning/materials/<slug>.html and returns the path.
"""
from __future__ import annotations

import html
import re
import time
from pathlib import Path

_TEMPLATE = """<html><head><meta charset='utf-8'><title>{title}</title><style>
:root {{ --accent:#3b6e8f; }}
body {{ font-family:-apple-system,Segoe UI,sans-serif; margin:0; background:#f6f7f9; color:#222 }}
header {{ background:var(--accent); color:#fff; padding:1.4rem 2rem }}
header h1 {{ margin:0; font-size:1.35rem }}
header small {{ opacity:.85 }}
main {{ max-width:46rem; margin:1.5rem auto; background:#fff; border-radius:8px;
       padding:1.6rem 2rem; box-shadow:0 1px 4px rgba(0,0,0,.08) }}
img,video {{ max-width:100%; border-radius:6px; margin:.6rem 0 }}
.selfcheck {{ background:#f0f6ea; border-left:4px solid #4a7; padding:.8rem 1rem;
             border-radius:0 6px 6px 0; margin-top:1.4rem }}
.selfcheck h2 {{ margin:0 0 .4rem; font-size:1rem }}
footer {{ text-align:center; color:#888; font-size:.8rem; margin:1.2rem 0 }}
code {{ background:#eef; padding:.1rem .3rem; border-radius:3px }}
</style></head><body>
<header><h1>{title}</h1><small>concept: {kc} &middot; generated by oh-my-brain</small></header>
<main>
{media}
{body}
{selfcheck}
</main>
<footer>local file &middot; no data leaves this machine</footer>
</body></html>"""


def _slug(title: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return s or f"material-{int(time.time())}"


def build_material_page(root: Path | str, *, title: str, kc: str, body_html: str,
                        image: str | None = None, video: str | None = None,
                        questions: list[str] | None = None) -> Path:
    root = Path(root)
    out_dir = root / "learning" / "materials"
    out_dir.mkdir(parents=True, exist_ok=True)

    media = ""
    if image:
        media += f"<img src='{html.escape(image)}' alt='{html.escape(title)}'>"
    if video:
        media += (f"<video controls src='{html.escape(video)}'>"
                  f"video: {html.escape(video)}</video>")

    selfcheck = ""
    if questions:
        items = "".join(f"<li>{html.escape(q)}</li>" for q in questions)
        selfcheck = (f"<div class='selfcheck'><h2>Check yourself</h2>"
                     f"<ol>{items}</ol>"
                     f"<small>Answers are not shown here on purpose; reply to the "
                     f"agent and it will grade you.</small></div>")

    out = out_dir / f"{_slug(title)}.html"
    out.write_text(_TEMPLATE.format(
        title=html.escape(title), kc=html.escape(kc),
        media=media, body=body_html, selfcheck=selfcheck), encoding="utf-8")
    return out
